### ISSUE TITLE
labels

### ISSUE THREAD

**Issue by pavelxx1** [Xx-Ashutosh-xX/CNN-TA#3]
HI
I can't understand , how to properly mark up indicator-labels i.e prepare images for training?
 thanks

**Comment by Xx-Ashutosh-xX** [comment]
see this https://github.com/Xx-Ashutosh-xX/CNN-TA#22-labelling
![alt](https://www.researchgate.net/profile/Omer-Sezer/publication/316848946/figure/fig1/AS:616352616296477@1523961323822/Labelling-Points-with-Window.png)

**Comment by pavelxx1** [comment]
thx, can you provide your labeled pic, for education?
thx!

**Comment by Xx-Ashutosh-xX** [comment]
Check this out : https://github.com/Xx-Ashutosh-xX/CNN-TA/tree/main/Graphs/sample

I was planning to add them but totally forgot about it.
